name: 'PFM-Upstream-Sync'

env:
  UPSTREAM_REPO: 'https://github.com/lobehub/lobe-chat.git'
  UPSTREAM_BRANCH: main
  TARGET_BRANCH: main
  MATCH_TAG: 'v*'
  EXCLUDE_TAG: '*-nightly*'

on:
  schedule:
    - cron: "0 20 * * *" # 每天04点
    - cron: "0 8 * * *" # 每天16点
  workflow_dispatch:

concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

permissions: write-all

jobs:
  Sync_Latest_From_UpStream:
    name: '同步上游仓库最新提交'
    runs-on: ubuntu-latest
    outputs:
      has_new_commits: ${{ steps.sync.outputs.has_new_commits }}
      has_match_tags: ${{ steps.sync.outputs.has_match_tags }}
      tag: ${{ steps.sync.outputs.tag }}

    steps:
      - name: '同步变化'
        id: sync
        uses: PFM-PowerForMe/PFM-Action-SYNC@main
        with:
          upstream_repo_url: ${{ env.UPSTREAM_REPO }}
          upstream_sync_branch: ${{ env.UPSTREAM_BRANCH }}
          target_sync_branch: ${{ env.TARGET_BRANCH }}
          target_repo_token: ${{ secrets.SYNC_TOKEN }}
          match_tag: ${{ env.MATCH_TAG }}
          exclude_tag: ${{ env.EXCLUDE_TAG }}

      - name: '同步失败'
        if: failure()
        run: |
          echo "[Error] 由于上游仓库工作流文件的更改，GitHub 已自动暂停了计划的自动更新。您需要手动同步您的复刻。"
          exit 1

  Call-next-workflow:
    needs: Sync_Latest_From_UpStream
    if: needs.Sync_Latest_From_UpStream.outputs.has_match_tags == 'true'
    permissions: write-all
    uses: ./.github/workflows/custom-container-build.yml
    with:
      tag: ${{ needs.Sync_Latest_From_UpStream.outputs.tag }}
    secrets: inherit